# Generated by Django 2.1 on 2021-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbuser', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=150)),
            ],
        ),
    ]
