# Generated by Django 2.1 on 2021-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('status', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=180)),
            ],
        ),
    ]
